#!/bin/bash

# 1. Aseguramos que no haya procesos zombies en el puerto 8050
fuser -k 8050/tcp || true

# 2. Lanzamos el dashboard en segundo plano con nohup para que no se muera
nohup python app.py > output.log 2>&1 &

# 3. Le damos unos segundos para que Flask/Dash estabilice el socket
sleep 5
